/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as GraficosRouteImport } from './routes/graficos'
import { Route as NovoRouteImport } from './routes/novo'
import { Route as RegistrosIndexRouteImport } from './routes/registros.index'
import { Route as RegistrosSlugRouteImport } from './routes/registros.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GraficosRoute = GraficosRouteImport.update({
  id: '/graficos',
  path: '/graficos',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoRoute = NovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrosIndexRoute = RegistrosIndexRouteImport.update({
  id: '/registros/',
  path: '/registros/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrosSlugRoute = RegistrosSlugRouteImport.update({
  id: '/registros/$slug',
  path: '/registros/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/graficos': typeof GraficosRoute
  '/novo': typeof NovoRoute
  '/registros/$slug': typeof RegistrosSlugRoute
  '/registros/': typeof RegistrosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/graficos': typeof GraficosRoute
  '/novo': typeof NovoRoute
  '/registros/$slug': typeof RegistrosSlugRoute
  '/registros': typeof RegistrosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/graficos': typeof GraficosRoute
  '/novo': typeof NovoRoute
  '/registros/$slug': typeof RegistrosSlugRoute
  '/registros/': typeof RegistrosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/graficos' | '/novo' | '/registros/$slug' | '/registros/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/graficos' | '/novo' | '/registros/$slug' | '/registros'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/graficos'
    | '/novo'
    | '/registros/$slug'
    | '/registros/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  GraficosRoute: typeof GraficosRoute
  NovoRoute: typeof NovoRoute
  RegistrosSlugRoute: typeof RegistrosSlugRoute
  RegistrosIndexRoute: typeof RegistrosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graficos': {
      id: '/graficos'
      path: '/graficos'
      fullPath: '/graficos'
      preLoaderRoute: typeof GraficosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo': {
      id: '/novo'
      path: '/novo'
      fullPath: '/novo'
      preLoaderRoute: typeof NovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registros/': {
      id: '/registros/'
      path: '/registros'
      fullPath: '/registros/'
      preLoaderRoute: typeof RegistrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registros/$slug': {
      id: '/registros/$slug'
      path: '/registros/$slug'
      fullPath: '/registros/$slug'
      preLoaderRoute: typeof RegistrosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  GraficosRoute: GraficosRoute,
  NovoRoute: NovoRoute,
  RegistrosSlugRoute: RegistrosSlugRoute,
  RegistrosIndexRoute: RegistrosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
